# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/hassio-addons/base:14.0.0"
  amd64: "ghcr.io/hassio-addons/base:14.0.0"
  armhf: "ghcr.io/hassio-addons/base:14.0.0"
  armv7: "ghcr.io/hassio-addons/base:14.0.0"
  i386: "ghcr.io/hassio-addons/base:14.0.0"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Airplanes Live API"
  org.opencontainers.image.description: "Track live airplane data and expose it as Home Assistant entities via MQTT"
  org.opencontainers.image.source: "https://github.com/BenCos17/airplanesliveHA"
  org.opencontainers.image.licenses: "MIT"
args:
  TEMPIO_VERSION: "2021.09.0"
