name: "Airplanes Live API Add-on"
description: "An add-on to track live airplane data and expose it as a Home Assistant entity via MQTT."
version: "1.2.6"
slug: "airplanes_live_api"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000
options:
  update_interval: 10  # Update interval in seconds
  mqtt_broker: "mqtt://localhost"  # MQTT broker URL
  mqtt_topic: "airplanes/live"  # Base topic for publishing data
schema:
  update_interval: int
  mqtt_broker: str
  mqtt_topic: str