name: "Airplanes Live API Add-on"
description: "An add-on to track live airplane data and expose it as a Home Assistant entity via MQTT."
version: "1.3.14
slug: "airplanes_live_api"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
    "8000/tcp": 8000
image: "ghcr.io/bencos17/airplanes_live_api_{arch}"
options:
  update_interval: 10
  mqtt_broker: core-mosquitto
  mqtt_port: 1883
  mqtt_topic: airplanes/live
  mqtt_username: ""
  mqtt_password: ""
  api_url: "https://api.airplanes.live/v2/point"
  latitude: 53.2707
  longitude: -9.0568
  radius: 50
schema:
  update_interval: int
  mqtt_broker: str
  mqtt_port: int
  mqtt_topic: str
  mqtt_username: str
  mqtt_password: str
  api_url: str
  latitude: float
  longitude: float
  radius: int