options:
  update_interval: 10
  mqtt_broker: core-mosquitto
  mqtt_port: 1883
  mqtt_topic: airplanes/live
  mqtt_username: ""
  mqtt_password: ""
  api_url: "https://airplanes.live/api/point"
  latitude: 53.2707
  longitude: -9.0568
  radius: 50
schema:
  update_interval: int
  mqtt_broker: str
  mqtt_port: int
  mqtt_topic: str
  mqtt_username: str
  mqtt_password: str
  api_url: str
  latitude: float
  longitude: float
  radius: int