name: "AirplanesliveHA"
description: "An add-on to track live airplane data."
version: "1.0.0"
slug: "airplanes_live"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000
options:
  update_interval: 10  # Update interval in seconds
schema:
  update_interval: int